PRODUCT_VERSION_MAJOR = 20
PRODUCT_VERSION_MINOR = 0

ifeq ($(LINEAGE_VERSION_APPEND_TIME_OF_DAY),true)
    LINEAGE_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)
else
    LINEAGE_BUILD_DATE := $(shell date -u +%Y%m%d)
endif

# Set LINEAGE_BUILDTYPE from the env RELEASE_TYPE, for jenkins compat

ifndef LINEAGE_BUILDTYPE
    ifdef RELEASE_TYPE
        # Starting with "LINEAGE_" is optional
        RELEASE_TYPE := $(shell echo $(RELEASE_TYPE) | sed -e 's|^LINEAGE_||g')
        LINEAGE_BUILDTYPE := $(RELEASE_TYPE)
    endif
endif

# Filter out random types, so it'll reset to KUSUMA
ifeq ($(filter KUSUMA,$(LINEAGE_BUILDTYPE)),)
    LINEAGE_BUILDTYPE := KUSUMA
    LINEAGE_EXTRAVERSION :=
endif

LINEAGE_VERSION_SUFFIX := $(LINEAGE_BUILD_DATE)-$(LINEAGE_BUILDTYPE)$(LINEAGE_EXTRAVERSION)-$(LINEAGE_BUILD)

# Internal version
LINEAGE_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_VERSION_SUFFIX)

# Display version
LINEAGE_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(LINEAGE_VERSION_SUFFIX)

# Extra version
EXTRA_PRODUCT_VERSION_NUMBER = 6
EXTRA_PRODUCT_VERSION_CODENAME = Fantom
EXTRA_PRODUCT_VERSION_URL = https://youtu.be/RQbs99v1K6Q

EXTRA_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_BUILD_DATE)-$(LINEAGE_BUILDTYPE)-$(EXTRA_PRODUCT_VERSION_NUMBER)$(LINEAGE_EXTRAVERSION)-$(LINEAGE_BUILD)
